In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv("player_mvp_stats.csv")

In [32]:
stats.sort_values("Share", ascending=False).head(20)[["Player","Year","Share"]]

                      Player  Year  Share
6640           Stephen Curry  2016  1.000
15157           LeBron James  2013  0.998
143         Shaquille O'Neal  2000  0.998
16040          Kevin Garnett  2004  0.991
12143         Michael Jordan  1996  0.986
7429            Kevin Durant  2014  0.986
6620            LeBron James  2010  0.980
14194           Derrick Rose  2011  0.977
6603            LeBron James  2009  0.969
812             Nikola Jokić  2021  0.961
1185            James Harden  2018  0.955
14364  Giannis Antetokounmpo  2020  0.952
11535         Michael Jordan  1992  0.938
869             Nikola Jokić  2024  0.935
12171         Michael Jordan  1998  0.934
13249  Giannis Antetokounmpo  2019  0.932
11522         Michael Jordan  1991  0.928
7146           Stephen Curry  2015  0.922
15976            Joel Embiid  2023  0.915
1286           Allen Iverson  2001  0.904

In [4]:
del stats["Unnamed: 0"]

In [5]:
pd.isnull(stats).sum()

Player        0
Age           0
Pos           0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          68
3P            0
3PA           0
3P%        2163
2P            0
2PA           0
2P%         118
eFG%         68
FT            0
FTA           0
FT%         603
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Tm            0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [6]:
stats[pd.isnull(stats["3P%"])]

,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,3P,...,Share,Tm,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
2,Elden Campbell,22,PF,52,0,7.3,1.1,2.4,0.455,0.0,...,0.0,LAL,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,25,PF,26,0,4.2,0.7,1.9,0.340,0.0,...,0.0,LAL,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
18,Jack Haley,28,C,49,9,8.0,0.6,1.7,0.369,0.0,...,0.0,LAL,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
20,Keith Owens,22,SF,20,0,4.0,0.5,1.6,0.281,0.0,...,0.0,LAL,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
30,Benoit Benjamin,28,C,59,6,12.8,2.3,4.6,0.491,0.0,...,0.0,LAL,Los Angeles Lakers,39,43,0.476,23.0,104.2,105.5,-1.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16351,Evan Eschmeyer,24,C,31,5,12.0,1.2,2.3,0.528,0.0,...,0.0,NJN,New Jersey Nets,31,51,0.378,21.0,98.0,99.0,-1.18
16352,Gheorghe Mureșan,28,C,30,2,8.9,1.4,3.0,0.456,0.0,...,0.0,NJN,New Jersey Nets,31,51,0.378,21.0,98.0,99.0,-1.18
16354,Jim McIlvaine,27,C,66,53,15.9,1.0,2.3,0.416,0.0,...,0.0,NJN,New Jersey Nets,31,51,0.378,21.0,98.0,99.0,-1.18
16360,Mark Hendrickson,25,PF,15,0,4.7,0.3,0.5,0.625,0.0,...,0.0,NJN,New Jersey Nets,31,51,0.378,21.0,98.0,99.0,-1.18
16361,Michael Cage,38,C,20,7,12.1,0.6,1.2,0.500,0.0,...,0.0,NJN,New Jersey Nets,31,51,0.378,21.0,98.0,99.0,-1.18

In [7]:
stats = stats.fillna(0)

In [8]:
stats.columns

Index(['Player', 'Age', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Tm', 'Team', 'W', 'L', 'W/L%', 'GB',
       'PS/G', 'PA/G', 'SRS'],
      dtype='object')

In [36]:
predictors = [ 'Age',  'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 'L', 'W/L%', 'GB',
       'PS/G', 'PA/G', 'SRS']

In [64]:
train = stats[stats["Year"] < 2024]

In [65]:
test = stats[stats["Year"] == 2024]

In [66]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [67]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [68]:
predictions = reg.predict(test[predictors])

In [69]:
predictions = pd.DataFrame(predictions, columns =["predictions"], index=test.index)

In [70]:
predictions

       predictions
229       0.000799
230      -0.019423
231       0.021318
232       0.007332
233      -0.013820
...            ...
14780    -0.008425
14781     0.001567
14782     0.001573
14783    -0.007702
14784    -0.019519

[572 rows x 1 columns]

In [71]:
combination = pd.concat([test[["Player","Share","Year"]], predictions], axis=1)

In [72]:
combination.sort_values("Share", ascending=False).head(10)

                        Player  Share  Year  predictions
869               Nikola Jokić  0.935  2024     0.172856
1562   Shai Gilgeous-Alexander  0.646  2024     0.168506
365                Luka Dončić  0.572  2024     0.188461
236      Giannis Antetokounmpo  0.194  2024     0.212369
4278             Jalen Brunson  0.143  2024     0.099011
3253              Jayson Tatum  0.087  2024     0.113595
9289           Anthony Edwards  0.018  2024     0.088176
4724          Domantas Sabonis  0.003  2024     0.097295
13159             Kevin Durant  0.001  2024     0.102024
11074          Cade Cunningham  0.000  2024     0.039287

In [73]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.002473615046289213

In [80]:
combination = combination.sort_values("Share", ascending=False)
combination["Rk"] = list(range(1, combination.shape[0]+1))

In [81]:
combination.head(10)

                        Player  Share  Year  predictions  Rk
869               Nikola Jokić  0.935  2024     0.172856   1
1562   Shai Gilgeous-Alexander  0.646  2024     0.168506   2
365                Luka Dončić  0.572  2024     0.188461   3
236      Giannis Antetokounmpo  0.194  2024     0.212369   4
4278             Jalen Brunson  0.143  2024     0.099011   5
3253              Jayson Tatum  0.087  2024     0.113595   6
9289           Anthony Edwards  0.018  2024     0.088176   7
4724          Domantas Sabonis  0.003  2024     0.097295   8
13159             Kevin Durant  0.001  2024     0.102024   9
11074          Cade Cunningham  0.000  2024     0.039287  10

In [84]:
combination = combination.sort_values("predictions",ascending=False)
combination["Predicted_Rk"] = list(range(1,combination.shape[0]+1))

In [86]:
combination.head(10)

                        Player  Share  Year  predictions   Rk  Predicted_Rk
236      Giannis Antetokounmpo  0.194  2024     0.212369    4             1
14607              Joel Embiid  0.000  2024     0.206397  215             2
365                Luka Dončić  0.572  2024     0.188461    3             3
869               Nikola Jokić  0.935  2024     0.172856    1             4
1562   Shai Gilgeous-Alexander  0.646  2024     0.168506    2             5
9200             Anthony Davis  0.000  2024     0.134625   85             6
9212              LeBron James  0.000  2024     0.128517  123             7
3253              Jayson Tatum  0.087  2024     0.113595    6             8
12461        Victor Wembanyama  0.000  2024     0.104871   57             9
13159             Kevin Durant  0.001  2024     0.102024    9            10

In [88]:
combination.sort_values("Share", ascending=False).head(15)

                        Player  Share  Year  predictions   Rk  Predicted_Rk
869               Nikola Jokić  0.935  2024     0.172856    1             4
1562   Shai Gilgeous-Alexander  0.646  2024     0.168506    2             5
365                Luka Dončić  0.572  2024     0.188461    3             3
236      Giannis Antetokounmpo  0.194  2024     0.212369    4             1
4278             Jalen Brunson  0.143  2024     0.099011    5            12
3253              Jayson Tatum  0.087  2024     0.113595    6             8
9289           Anthony Edwards  0.018  2024     0.088176    7            17
4724          Domantas Sabonis  0.003  2024     0.097295    8            13
13159             Kevin Durant  0.001  2024     0.102024    9            10
13556             Jake LaRavia  0.000  2024    -0.009854  225           393
14388              D.J. Carton  0.000  2024    -0.009632  177           388
12448           David Duke Jr.  0.000  2024    -0.009387   44           382
6393                Kobe Brown  0.000  2024    -0.009404  489           383
1465             Aaron Nesmith  0.000  2024    -0.009517  318           384
526                 Seth Lundy  0.000  2024    -0.009534  419           385

In [93]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions",ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found+=1
            ps.append(found/seen)
        seen+= 1
    return sum(ps) / len(ps)

In [94]:
find_ap(combination)

0.7266666666666667

In [95]:
years = list(range(1991, 2025))

In [97]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors], train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions,columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player","Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [98]:
sum(aps) / len(aps)

0.7197694748378854

In [101]:
def add_ranks(combination):
    combination = combination.sort_values("Share", ascending=False)
    combination["Rk"] = list(range(1, combination.shape[0]+1))
    combination = combination.sort_values("predictions",ascending=False)
    combination["Predicted_Rk"] = list(range(1,combination.shape[0]+1))
    combination["Diff"] = combination["Rk"] - combination["Predicted_Rk"]
    return combination

In [133]:
ranking = add_ranks(all_predictions[19])
ranking[ranking["Rk"] < 9].sort_values("Rk", ascending = True)

                  Player  Share  predictions  Rk  Predicted_Rk  Diff
7146       Stephen Curry  0.922     0.112420   1             6    -5
15599       James Harden  0.720     0.121439   2             5    -3
4623        LeBron James  0.425     0.141302   3             2     1
7452   Russell Westbrook  0.271     0.127944   4             3     1
4943       Anthony Davis  0.156     0.157180   5             1     4
11172         Chris Paul  0.095     0.104845   6             8    -2
5303   LaMarcus Aldridge  0.005     0.078926   7            16    -9
11169      Blake Griffin  0.002     0.096101   8             9    -1

In [134]:
def backtest(stats, model, year, predictors):
    aps = []
    all_predictions = []
    for year in years[5:]:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors], train["Share"])
        predictions = reg.predict(test[predictors])
        predictions = pd.DataFrame(predictions,columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player","Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps)/len(aps), aps, pd.concat(all_predictions)

In [135]:
mean_ap, aps, all_predictions = backtest(stats,reg,years[5:],predictors)

In [136]:
mean_ap

0.7197694748378854

In [138]:
all_predictions [all_predictions["Rk"] < 9].sort_values("Rk", ascending = True).head(10)

                      Player  Share  predictions  Rk  Predicted_Rk  Diff
14364  Giannis Antetokounmpo  0.952     0.239100   1             1     0
2100             Karl Malone  0.701     0.126884   1             2    -1
13249  Giannis Antetokounmpo  0.932     0.218551   1             1     0
7844             Kobe Bryant  0.873     0.108810   1             8    -7
812             Nikola Jokić  0.961     0.154324   1             3    -2
143         Shaquille O'Neal  0.998     0.232297   1             1     0
15157           LeBron James  0.998     0.195617   1             1     0
6640           Stephen Curry  1.000     0.169207   1             1     0
1286           Allen Iverson  0.904     0.117858   1             6    -5
7146           Stephen Curry  0.922     0.112420   1             6    -5

In [142]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis =1).sort_values(0, ascending=False)

           0     1
13  0.122845  eFG%
29  0.031241  W/L%
18  0.029938   DRB
17  0.016404   ORB
10  0.015194    2P
21  0.012396   STL
12  0.010948   2P%
15  0.010340   FTA
22  0.010202   BLK
25  0.007543   PTS
20  0.006678   AST
5   0.003416   FGA
4   0.001690    FG
30  0.000261    GB
0   0.000233   Age
32  0.000169  PA/G
27  0.000130     W
1   0.000088     G
2   0.000003    GS
26 -0.000185  Year
28 -0.000300     L
33 -0.000366   SRS
31 -0.000906  PS/G
24 -0.002533    PF
7  -0.003794    3P
3  -0.003907    MP
16 -0.005348   FT%
14 -0.006567    FT
8  -0.007730   3PA
23 -0.008648   TOV
9  -0.008977   3P%
11 -0.014584   2PA
19 -0.022445   TRB
6  -0.191294   FG%

In [148]:
stat_ratios = stats[["PTS", "AST", "STL","BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [149]:
stat_ratios

                 PTS       AST       STL       BLK        3P  Year
Year
1991 0      1.010123  0.420887  0.959858  0.667435  0.509908   1.0
     1      1.609536  1.028835  1.645471  0.667435  4.589168   1.0
     2      0.310807  0.093530  0.274245  1.557349  0.000000   1.0
     3      0.199804  0.187061  0.274245  0.000000  0.000000   1.0
     4      2.375453  1.636782  1.782593  0.889914  1.529723   1.0
...              ...       ...       ...       ...       ...   ...
2025 16173  0.146278  0.143869  0.000000  0.000000  0.286361   1.0
     16174  0.000000  0.479562  0.000000  0.000000  0.000000   1.0
     16175  0.000000  0.335693  0.000000  0.000000  0.000000   1.0
     16176  0.731391  0.575474  0.897240  0.744115  1.145445   1.0
     16177  2.621757  2.014159  1.196321  0.496077  3.054521   1.0

[16382 rows x 6 columns]

In [150]:
 stats[["PTS_T", "AST_R", "STL_R","BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL","BLK", "3P"]]

TypeError: incompatible index of inserted column with frame index